In [5]:
from keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
### Vocabulary size
voc_size=10000

In [9]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[6288, 1285, 1805, 3588], [6288, 1285, 1805, 395], [6288, 5141, 1805, 9001], [9176, 1238, 4652, 186, 7724], [9176, 1238, 4652, 186, 3509], [7406, 6288, 7334, 1805, 8228], [441, 3165, 8140, 186]]


In [10]:
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_lengths = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_lengths)
print(embedded_docs)

[[   0    0    0    0 6288 1285 1805 3588]
 [   0    0    0    0 6288 1285 1805  395]
 [   0    0    0    0 6288 5141 1805 9001]
 [   0    0    0 9176 1238 4652  186 7724]
 [   0    0    0 9176 1238 4652  186 3509]
 [   0    0    0 7406 6288 7334 1805 8228]
 [   0    0    0    0  441 3165 8140  186]]


In [13]:
dim = 15

In [16]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_lengths))
model.compile('adam', 'mse')

In [17]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 15)             150000    
                                                                 
Total params: 150000 (585.94 KB)
Trainable params: 150000 (585.94 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 293ms/step
[[[-4.69059460e-02  4.02233936e-02  4.58120443e-02  4.48181480e-03
   -1.97490212e-02  1.96138769e-03 -2.07321774e-02  4.34602015e-02
   -3.49855796e-02 -1.90016516e-02 -1.68347247e-02 -1.38491169e-02
    1.75798573e-02 -2.25312468e-02 -2.73404121e-02]
  [-4.69059460e-02  4.02233936e-02  4.58120443e-02  4.48181480e-03
   -1.97490212e-02  1.96138769e-03 -2.07321774e-02  4.34602015e-02
   -3.49855796e-02 -1.90016516e-02 -1.68347247e-02 -1.38491169e-02
    1.75798573e-02 -2.25312468e-02 -2.73404121e-02]
  [-4.69059460e-02  4.02233936e-02  4.58120443e-02  4.48181480e-03
   -1.97490212e-02  1.96138769e-03 -2.07321774e-02  4.34602015e-02
   -3.49855796e-02 -1.90016516e-02 -1.68347247e-02 -1.38491169e-02
    1.75798573e-02 -2.25312468e-02 -2.73404121e-02]
  [-4.69059460e-02  4.02233936e-02  4.58120443e-02  4.48181480e-03
   -1.97490212e-02  1.96138769e-03 -2.07321774e-02  4.34602015e-02
   -3.49855796e-02 -1.90016516e-02 -1.68347247e-02 -1.

In [19]:
print(embedded_docs[0])  
print(model.predict(embedded_docs)[0])

[   0    0    0    0 6288 1285 1805 3588]
1/1 [==============================] - 0s 39ms/step
[[-0.04690595  0.04022339  0.04581204  0.00448181 -0.01974902  0.00196139
  -0.02073218  0.0434602  -0.03498558 -0.01900165 -0.01683472 -0.01384912
   0.01757986 -0.02253125 -0.02734041]
 [-0.04690595  0.04022339  0.04581204  0.00448181 -0.01974902  0.00196139
  -0.02073218  0.0434602  -0.03498558 -0.01900165 -0.01683472 -0.01384912
   0.01757986 -0.02253125 -0.02734041]
 [-0.04690595  0.04022339  0.04581204  0.00448181 -0.01974902  0.00196139
  -0.02073218  0.0434602  -0.03498558 -0.01900165 -0.01683472 -0.01384912
   0.01757986 -0.02253125 -0.02734041]
 [-0.04690595  0.04022339  0.04581204  0.00448181 -0.01974902  0.00196139
  -0.02073218  0.0434602  -0.03498558 -0.01900165 -0.01683472 -0.01384912
   0.01757986 -0.02253125 -0.02734041]
 [ 0.01203394 -0.02687211 -0.02657299  0.03705854  0.01748283 -0.02769244
  -0.0097637  -0.03172084 -0.04361812 -0.00550491  0.04397767 -0.00748861
   0.02141